title: Nabeel Maklai
logo: /assets/Nabil.png
description: Data-Driven Mechanical Engineer and Data Scientist
[![LinkedIn Logo](/assets/linkedin.png)](https://www.linkedin.com/in/nabeelismaeelmaklai/)
#show_downloads: true
theme: jekyll-theme-minimal
#/assets/linkedin.png
